name: Build Resource Pack
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: cd pack && zip -r ../pack.zip assets/ Pack.mcmeta
      - uses: ncipollo/release-action@v1
        with:
          tag: latest
          allowUpdates: true
          removeArtifacts: true
          replacesArtifacts: true
          artifacts: pack.zip
          artifactContentType: application/zip
          body: Auto-built resource pack
          omitBodyDuringUpdate: true
