name: Build Resource Pack
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: python -c "import zipfile, os; os.chdir('pack'); zf = zipfile.ZipFile('../pack.zip', 'w', zipfile.ZIP_DEFLATED); [zf.write(r, r) for r in ['pack.mcmeta']]; [zf.write(os.path.join(dp, f), os.path.join(dp, f)) for dp, dn, fn in os.walk('assets') for f in fn]; zf.close()"
      - uses: ncipollo/release-action@v1
        with:
          tag: latest
          allowUpdates: true
          removeArtifacts: true
          replacesArtifacts: true
          artifacts: pack.zip
          artifactContentType: application/zip
          body: Auto-built resource pack
          omitBodyDuringUpdate: true
