name: Build Resource Pack
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: cd pack && zip -r ../pack.zip assets/ Pack.mcmeta
      - uses: softprops/action-gh-release@v2
        with:
          files: pack.zip